import type { HalftoneSceneConfig } from "./types";

export const oneHalftoneSceneConfig: HalftoneSceneConfig = {
  aspectRatio: 1.66,
  width: {
    min: 320,
    max: 1280,
    viewportRatio: 1,
  },
  scroll: {
    start: "55% 60%",
    end: "80% 10%",
    scrub: true,
    markers: process.env.NODE_ENV === "development" ? true : false,
  },
  baseLayerIndex: 1,
  layers: [
    {
      id: "grit-bg",
      imageSrc: "/img/optimized/linesbg.webp",
      imageFit: "cover",
      placement: "background",
      className: "opacity-10",
      padding: 0.01,
      params: {
        initial: {
          halftoneSize: "5%",
          dotSpacing: ".1%",
          rgbOffset: "5%",
          rgbOffsetAngle: 45,
          effectIntensity: 0.1,
          patternRotation: 35,
          zoom: 1,
          translateY: "0%",
        },
        target: {
          halftoneSize: "8%",
          dotSpacing: "0.3%",
          rgbOffset: "25%",
          rgbOffsetAngle: 5,
          effectIntensity: 0.18,
          patternRotation: 55,
          zoom: 0.5,
          translateY: "0%",
        },
      },
    },
    {
      id: "planet",
      imageSrc: "/img/optimized/planet-cropped.webp",
      imageFit: "contain",
      className: "",
      padding: 0.05,
      params: {
        initial: {
          halftoneSize: "6%",
          dotSpacing: "0.2%",
          rgbOffset: "0%",
          rgbOffsetAngle: 0,
          effectIntensity: 0.2,
          patternRotation: 55,
          zoom: 1,
          brightness: 1.2,
          contrast: 1,
          translateY: "0%",
        },
        target: {
          halftoneSize: "4%",
          dotSpacing: "0.1%",
          rgbOffset: "25%",
          rgbOffsetAngle: 0,
          effectIntensity: 0.35,
          patternRotation: 40,
          zoom: 0.65,
          brightness: 1,
          contrast: 1,
          translateY: "0%",
        },
      },
    },
  ],
};
