import type { HalftoneSceneConfig } from "./types";

export const oneHalftoneSceneConfig: HalftoneSceneConfig = {
  aspectRatio: 1.5,
  width: {
    min: 320,
    max: 1280,
    viewportRatio: 1,
  },
  scroll: {
    start: "30% 60%",
    end: "40% 40%",
    scrub: true,
    markers: true,
  },
  baseLayerIndex: 1,
  padding: 0.08,
  layers: [
    {
      id: "grit-bg",
      imageSrc: "/img/optimized/linesbg.webp",
      imageFit: "cover",
      placement: "background",
      className: "opacity-10",
      params: {
        initial: {
          halftoneSize: "5%",
          dotSpacing: ".1%",
          rgbOffset: "5%",
          rgbOffsetAngle: 45,
          effectIntensity: 0.1,
          patternRotation: 35,
          zoom: 1,
          translateY: "0%",
        },
        target: {
          halftoneSize: "8%",
          dotSpacing: "0.3%",
          rgbOffset: "50%",
          rgbOffsetAngle: 5,
          effectIntensity: 0.18,
          patternRotation: 55,
          zoom: 0.4,
          translateY: "0%",
        },
      },
    },
    {
      id: "planet",
      imageSrc: "/img/optimized/planet-cropped.webp",
      imageFit: "contain",
      className: "",
      params: {
        initial: {
          halftoneSize: "6%",
          dotSpacing: "0.2%",
          rgbOffset: "5%",
          rgbOffsetAngle: 45,
          effectIntensity: 0.2,
          patternRotation: 55,
          zoom: 1,
          brightness: 1.1,
          contrast: 1.05,
          translateY: "10%",
        },
        target: {
          halftoneSize: "4%",
          dotSpacing: "0.1%",
          rgbOffset: "2%",
          rgbOffsetAngle: 95,
          effectIntensity: 0.35,
          patternRotation: 40,
          zoom: 1,
          brightness: 1.15,
          contrast: 1.1,
          translateY: "20%",
        },
      },
    },
  ],
};
