import type { HalftoneSceneConfig } from "./types";

export const oneHalftoneSceneConfig: HalftoneSceneConfig = {
  aspectRatio: 1.32,
  width: {
    min: 320,
    max: 1280,
    viewportRatio: 0.85,
  },
  scroll: {
    start: "top 60%",
    end: "+=200%",
    scrub: 0.8,
    markers: false,
  },
  baseLayerIndex: 1,
  layers: [
    {
      id: "grit-bg",
      imageSrc: "/img/optimized/linesbg.webp",
      imageFit: "cover",
      placement: "background",
      className: "",
      params: {
        initial: {
          halftoneSize: "22%",
          dotSpacing: "0.5%",
          rgbOffset: "16%",
          rgbOffsetAngle: 25,
          effectIntensity: 0.1,
          patternRotation: 35,
          zoom: 2.3,
          translateY: "-8%",
        },
        target: {
          halftoneSize: "8%",
          dotSpacing: "0.3%",
          rgbOffset: "6%",
          rgbOffsetAngle: 5,
          effectIntensity: 0.18,
          patternRotation: 55,
          zoom: 1.05,
          translateY: "-45%",
        },
      },
    },
    {
      id: "planet",
      imageSrc: "/img/optimized/planet-cropped.webp",
      imageFit: "contain",
      className: "mix-blend-screen",
      params: {
        initial: {
          halftoneSize: "6%",
          dotSpacing: "0.2%",
          rgbOffset: "6%",
          rgbOffsetAngle: 90,
          effectIntensity: 0.2,
          patternRotation: 55,
          zoom: 1.2,
          brightness: 1.1,
          contrast: 1.05,
          translateY: "10%",
        },
        target: {
          halftoneSize: "4%",
          dotSpacing: "0.1%",
          rgbOffset: "2%",
          rgbOffsetAngle: 95,
          effectIntensity: 0.35,
          patternRotation: 40,
          zoom: 0.9,
          brightness: 1.15,
          contrast: 1.1,
          translateY: "100%",
        },
      },
    },
    {
      id: "figure",
      imageSrc: "/img/optimized/no-bg.webp",
      imageFit: "contain",
      className: "mix-blend-plus-lighter drop-shadow-2xl",
      params: {
        initial: {
          halftoneSize: "3%",
          dotSpacing: "0.08%",
          rgbOffset: "3%",
          rgbOffsetAngle: 120,
          effectIntensity: 0.45,
          patternRotation: 65,
          zoom: 1.4,
          brightness: 1.2,
          contrast: 1.2,
          translateY: "-6%",
        },
        target: {
          halftoneSize: "2%",
          dotSpacing: "0.04%",
          rgbOffset: "1%",
          rgbOffsetAngle: 160,
          effectIntensity: 0.8,
          patternRotation: 35,
          zoom: 0.85,
          brightness: 1.3,
          contrast: 1.15,
          translateY: "-30%",
        },
      },
    },
  ],
};
